# Pandas

In [162]:
import pandas as pd
pd.__version__

'2.3.1'

## Series

A Pandas <code>Series</code> is a one-dimensional array of indexed data. It can be created from a list or array as follows:

### Creating a series from list

In [163]:
data_pd = pd.Series([0.25, 0.5, 0.75, 1.0])
print("1: Pandas series from list: \n",data_pd)

1: Pandas series from list:
 0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

### Creating a series from numpy array

In [164]:
import numpy as np
numpy_arr = np.arange(5)
data_pd   = pd.Series(numpy_arr)
print("1: Pandas series from numpy array: \n", data_pd)  # notice default index

1: Pandas series from numpy array:
 0    0
1    1
2    2
3    3
4    4
dtype: int64

### Attributes

In [165]:
print("1: Data values: ", data_pd.values)  # numpy array 
print("2: Data index:  ", data_pd.index)  # range index is pandas object

1: Data values:  [0 1 2 3 4]
2: Data index:   RangeIndex(start=0, stop=5, step=1)

### Indexing

In [166]:
print("1: Data[1]:     ", data_pd[1])
print("2: Data[-2:]: \n", data_pd[-2:])  # slicing still works

# index is explicitly defined!  Unlike numpy which is implicitly defined

# errors, no index of -1
# print("Data[-1]: ", data_pd[-1])

1: Data[1]:      1
2: Data[-2:]:
 3    3
4    4
dtype: int64

### Letter indexing

In [167]:
# integer indexing is nasty!  try change to letters
data_pd = pd.Series([0.25, 0.5, 0.75, 1.0], 
                    index=['a', 'b', 'c', 'd'])

print("1: Data[-1]:  ", data_pd[-1])
print("2: Data['b']: ", data_pd['b'])

1: Data[-1]:   1.0
2: Data['b']:  0.5

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21252\469963077.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1: Data[-1]:  ", data_pd[-1])

### Combined indexing

In [168]:
index   = ['a', 'b', 'c', 'd', 3]
data_pd = pd.Series(numpy_arr, index = index)

print("1: Index['a']: ", data_pd['a'])
print("2: Index[3]:   ", data_pd[3])  # 3 is not position three but index 3!

1: Index['a']:  0
2: Index[3]:    4

### Pandas and dictionary

In [169]:
# since pandas index system looks like dictionary, it is no surprise
# that pandas can be created from dictionary, see this:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}

data_pd = pd.Series(some_population_dict)
print("1: Population['Vinh Long']: ", data_pd['Vinh Long'])

# also supports slicing!
print("2: Population['Sai Gon':'Vung Tau']: \n", data_pd['Sai Gon': 'Vung Tau'])

1: Population['Vinh Long']:  44444
2: Population['Sai Gon':'Vung Tau']:
 Sai Gon     11111
Vung Tau    22222
dtype: int64

### Pandas and scalar

In [170]:
# data can be scalar, which is repeated to fill the specified index
data_pd = pd.Series(5, index=[2, 3, 8])
print("1: Data pd scalar: \n", data_pd)

1: Data pd scalar:
 2    5
3    5
8    5
dtype: int64

## Dataframe

DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names.  DataFrame as a sequence of aligned Series objects.

### Create dataframe with two dict

In [171]:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}
some_area_dict = {'Sai Gon': 99999, 
                'Vung Tau': 88888,
                'Phan Thiet': 77777,
                'Vinh Long': 66666,
                 'Ben Tre': 33333}

states = pd.DataFrame({'population': some_population_dict,
                       'area': some_area_dict})
print(states)

            population   area
Sai Gon        11111.0  99999
Vung Tau       22222.0  88888
Phan Thiet     33333.0  77777
Vinh Long      44444.0  66666
Ben Tre            NaN  33333

### Indexing

In [172]:
print("Only Vung Tau to Sai Gon: ")
print(states['Vung Tau': 'Sai Gon'])

Only Vung Tau to Sai Gon:
Empty DataFrame
Columns: [population, area]
Index: []

In [173]:
print("Only population column: ")
print(states['Vung Tau': 'Sai Gon']['population'])
print(states['population']['Vung Tau': 'Sai Gon'])  # order does not matter; imagine as drill down

Only population column:
Series([], Name: population, dtype: float64)
Series([], Name: population, dtype: float64)

In [174]:
print("Only area column with everything")
print(states['area'])  # first way
print(states[:]['area']) # second way

Only area column with everything
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64

### Attributes

In [175]:
print("Index:        ", states.index)  # pandas index object
print("Index[-1]:    ", states.index[-1])  # pandas index object is similar to numpy array
print("Columns:      ", states.columns)  # pandas index object
print("Columns[0:1]: ", states.columns[0:1]) # notice how 1 is not included

Index:         Index(['Sai Gon', 'Vung Tau', 'Phan Thiet', 'Vinh Long', 'Ben Tre'], dtype='object')
Index[-1]:     Ben Tre
Columns:       Index(['population', 'area'], dtype='object')
Columns[0:1]:  Index(['population'], dtype='object')

### Other ways to create

In [176]:
# from series
population_series = pd.Series(some_population_dict)
pd_from_series    = pd.DataFrame(population_series, columns=['population'])  # since it's series, we need to pass column name, if not, it will be named 0
print("PD from series: \n", pd_from_series)

# from list of dicts
data              = [{'a': i, 'b': 2 * i} for i in range(3)]
pd_from_list_dict = pd.DataFrame(data, index=[1, 2, 3])
print("PD from list of dict: \n", pd_from_list_dict)

# from 2D numpy array
data_numpy    = np.random.rand(3, 2)
index         = ['a', 'b', 'c']
columns       = ['foo', 'bar']
pd_from_numpy = pd.DataFrame(data_numpy, index=index, columns=columns)
print("PD from numpy: \n", pd_from_numpy)

PD from series:
             population
Sai Gon          11111
Vung Tau         22222
Phan Thiet       33333
Vinh Long        44444
PD from list of dict:
    a  b
1  0  0
2  1  2
3  2  4
PD from numpy:
         foo       bar
a  0.528099  0.553388
b  0.283916  0.509581
c  0.543347  0.957468

 ## Series indexing/slicing/fancy Indexing

In [177]:
import pandas as pd
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index = ['a', 'b', 'c', 'd'])

print("Data:\n", data)

Data:
 a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

### Explicit vs. Implicit index

In [178]:
# explicit index
print("Explicit index: ", data['b'])

# also support implicit index, since we define index
print("Implicit index: ", data[-1])

Explicit index:  0.5
Implicit index:  1.0

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21252\675197797.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Implicit index: ", data[-1])

In [179]:
# slicing with explicit index (include c)
print("Data['a':'c']: \n", data['a':'c'])

# slicing with implicit index (exclude 2)
print("Data[0:2]: \n", data[0:2])

Data['a':'c']:
 a    0.25
b    0.50
c    0.75
dtype: float64
Data[0:2]:
 a    0.25
b    0.50
dtype: float64

### Adding values

In [180]:
# extend series by assigning new index value
data['e'] = 99
print("Data with e: \n", data)

Data with e:
 a     0.25
b     0.50
c     0.75
d     1.00
e    99.00
dtype: float64

### "in"

In [181]:
print("a in data?: ", 'a' in data)  # access keys

a in data?:  True

### keys()

In [182]:
print("All keys: ", data.keys()) # pandas index object

All keys:  Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

#### items()

In [183]:
print("All items: ", list(data.items())) # zip object

All items:  [('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0), ('e', 99.0)]

### values()

In [184]:
print("All values: ", data.values) # numpy array object

All values:  [ 0.25  0.5   0.75  1.   99.  ]

### masking

In [185]:
print("Data[(data > 0.3) & (data < 0.8)]: \n", data[(data>0.3) & (data < 0.8)])

Data[(data > 0.3) & (data < 0.8)]:
 b    0.50
c    0.75
dtype: float64

### fancy indexing

In [186]:
print("Data[['a', 'e']]: \n", data[['a', 'e']])

Data[['a', 'e']]:
 a     0.25
e    99.00
dtype: float64

### iloc vs. loc

In [187]:
# some precaution on the possible confusion if you use explicit integer index
# use explicit index when indexing
data = pd.Series(['a', 'b', 'c'], index=(1, 3, 5))
print("Data[1]: ", data[1])

# use implicit index when slicing
print("Data[1:3]: \n", data[1:3])

# due to this possible confusion due to explicit integer index, pandas
# provide loc and iloc
# loc uses explicit index
print("Data loc [1]: ", data.loc[1])
print("Data loc [1:3]: \n", data.loc[1:3])  # include 3 as well

#iloc uses implicit index
print("Data iloc [1]: ", data.iloc[1])
print("Data iloc [1:3]: \n", data.iloc[1:3])  # does not include 3

# always use iloc for implicit index, for no unnecessary confusion!

Data[1]:  a
Data[1:3]:
 3    b
5    c
dtype: object
Data loc [1]:  a
Data loc [1:3]:
 1    a
3    b
dtype: object
Data iloc [1]:  b
Data iloc [1:3]:
 3    b
5    c
dtype: object

## DataFrame indexing/slicing/fancy Indexing

In [188]:
some_population_dict = {'Sai Gon': 11111, 
                        'Vung Tau': 22222,
                        'Phan Thiet': 33333,
                        'Vinh Long': 44444}
some_area_dict = {'Sai Gon': 99999, 
                'Vung Tau': 88888,
                'Phan Thiet': 77777,
                'Vinh Long': 66666,
                 'Ben Tre': 33333}
data = pd.DataFrame({'pop': some_population_dict,
                       'area': some_area_dict})

print("==data==")
print(data)

==data==
                pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777
Vinh Long   44444.0  66666
Ben Tre         NaN  33333

### dictionary style access

In [189]:
# dataframe can be accessed via dictionary style indexing
print("==Area==")
print(data['area'])

==Area==
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64

### attribute style access

In [190]:
# we can also use attribute-style
print("==Area using attributes==")
print(data.area)
print("Data area is same: ", data.area is data['area'])

==Area using attributes==
Sai Gon       99999
Vung Tau      88888
Phan Thiet    77777
Vinh Long     66666
Ben Tre       33333
Name: area, dtype: int64
Data area is same:  True

### attribute style does not always work

In [191]:
# However!!, keep in mind that attribute style does not always work
# for example, pop is a method, thus data.pop will point to some method instead
print("==Do not use .pop!==")
print("Some pop method: \n", data.pop)
print("Data pop not the same: ", data.pop is data['pop'])

==Do not use .pop!==
Some pop method:
 <bound method DataFrame.pop of                 pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777
Vinh Long   44444.0  66666
Ben Tre         NaN  33333>
Data pop not the same:  False

### Feature engineering

In [192]:
print("==Feature engineering with density==")
data['density'] = data['pop'] / data['area']
print(data)

==Feature engineering with density==
                pop   area   density
Sai Gon     11111.0  99999  0.111111
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
Vinh Long   44444.0  66666  0.666667
Ben Tre         NaN  33333       NaN

### iloc and loc

In [193]:
# we cannot use data[0] since we do not have explicit index called 0, use iloc instead
print("==First row using iloc==")
print(data.iloc[0])

==First row using iloc==
pop        11111.000000
area       99999.000000
density        0.111111
Name: Sai Gon, dtype: float64

In [194]:
print("==First three rows, first two columns using iloc==")
print(data.iloc[:3, :2])

==First three rows, first two columns using iloc==
                pop   area
Sai Gon     11111.0  99999
Vung Tau    22222.0  88888
Phan Thiet  33333.0  77777

In [195]:
# use loc for explicit index
print("==Use loc for explicit index==")
print(data.loc[:'Sai Gon', :'pop'])

==Use loc for explicit index==
             pop
Sai Gon  11111.0

In [196]:
# chaining is possible for combine
print("==chain iloc and loc==")
print(data.loc[:'Sai Gon'].iloc[:, :2])

==chain iloc and loc==
             pop   area
Sai Gon  11111.0  99999

#### masking + fancy

In [197]:
print("==masking + fancy==")
print(data.loc[data.density > 20, ['pop', 'density']])

==masking + fancy==
Empty DataFrame
Columns: [pop, density]
Index: []

### Indexing vs. slicing

In [198]:
### some really important convention to keep in mind###
#1.  indexing refers to columns, while slicing refer to rows
print("==Indexing refer to columns==")
print(data['pop'])


print("==Slicing refer to rows==")
print(data['Vung Tau': 'Phan Thiet']) 


print("==Slicing can also use implicit integers==")
print(data[1:3])  # not including 3

print("==masking are done row-wise==")
print(data[data.density > 20])

==Indexing refer to columns==
Sai Gon       11111.0
Vung Tau      22222.0
Phan Thiet    33333.0
Vinh Long     44444.0
Ben Tre           NaN
Name: pop, dtype: float64
==Slicing refer to rows==
                pop   area   density
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
==Slicing can also use implicit integers==
                pop   area   density
Vung Tau    22222.0  88888  0.250000
Phan Thiet  33333.0  77777  0.428571
==masking are done row-wise==
Empty DataFrame
Columns: [pop, area, density]
Index: []

## Broadcasting

In [199]:
import pandas as pd
import numpy as np

rng = np.random.RandomState(42)
df  = pd.DataFrame(rng.randint(0, 10, (3, 4)), 
                 columns = ['A', 'B', 'C', 'D'])
df

   A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

### Basic broadcasting

In [200]:
df_new = np.sin(df * np.pi / 4) 
df_new

          A             B         C             D
0 -1.000000  7.071068e-01 -0.707107  1.224647e-16
1 -1.000000  7.071068e-01  1.000000 -1.000000e+00
2 -0.707107  1.224647e-16  0.707107 -7.071068e-01

### Index alignment

In [201]:
area = pd.Series({'Alaska': 111, 'Texas': 222,
                 'California': 333}, name = 'area')
population = pd.Series({'California' : 999, 'Texas': 888,
                       'New York': 777}, name = 'population')

#as you can see, any missing value will be replaced with NaN
print("==population / area==")
print(population / area)

==population / area==
Alaska        NaN
California    3.0
New York      NaN
Texas         4.0
dtype: float64

In [202]:
#similarly
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
print("==A + B==")
print(A + B)

==A + B==
0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [203]:
#we can use fill_value params in pd.add(pd)
print("==A.add(B, fill_value=0)==")  #any missing Nan values will be replaced with 0
print(A.add(B, fill_value = 0))

==A.add(B, fill_value=0)==
0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

### Dataframe and series

In [204]:
#Operation between df and series
#common operation is to find difference  of the entire df with one row or column
A  = rng.randint(10, size = (3, 4))
df = pd.DataFrame(A, columns=list('QRST'))
print("==df==")
print(df)

==df==
   Q  R  S  T
0  7  2  5  4
1  1  7  5  1
2  4  0  9  5

In [205]:
print("==df-df.iloc[0]==")
print(df - df.iloc[0])

==df-df.iloc[0]==
   Q  R  S  T
0  0  0  0  0
1 -6  5  0 -3
2 -3 -2  4  1

In [206]:
print("==column-wise==")  #cannot do - , since default is row-wise
print(df.subtract(df['R'], axis=0))

==column-wise==
   Q  R  S  T
0  5  0  3  2
1 -6  0 -2 -6
2  4  0  9  5

## Bài tập 1:
Tải file CSV howlongwelive.csv trong thư mục data vào một DataFrame. Có thể lấy từ kaggle

1. In ra 2 dòng đầu tiên và 2 dòng cuối cùng của DataFrame.

2. In ra kích thước (shape) của DataFrame.

3. In ra tên các đặc trưng (các cột) của DataFrame.

4. In ra bảng thống kê mô tả bằng hàm .describe().

5. Vì cột Hepatitis B có rất nhiều giá trị thiếu (NaN) và có mức tương quan cao với Diphtheria, hãy xóa cột Hepatitis B.
Đồng thời xóa cột Population do có quá nhiều giá trị NaN.

6. Chuyển đổi cột Status sang dạng số:

    0 cho Developing

    1 cho Developed

7. Đổi tên cột thinness 1-19 years thành thinness 10-19 years.

8. Lấy tất cả các cột ngoại trừ Life Expectancy, chuyển sang mảng NumPy và lưu vào biến X.

9. Lấy cột Life Expectancy, chuyển sang mảng NumPy và lưu vào biến y.

In [207]:
import pandas as pd
import numpy as np 
df = pd.read_csv("D:\HK252\DeepLearning\howlongwelive.csv")

In [208]:
# Step 1: In ra 2 dòng đầu tiên và 2 dòng cuối cùng
df.tail(2)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.0,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.0,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [209]:
# Step 2: In ra kích thước (shape) của DataFrame
df.shape

(2938, 22)

In [210]:
# Step 3: In ra tên các đặc trưng (các cột)
df.columns.tolist()

['Country',
 'Year',
 'Status',
 'Life expectancy ',
 'Adult Mortality',
 'infant deaths',
 'Alcohol',
 'percentage expenditure',
 'Hepatitis B',
 'Measles ',
 ' BMI ',
 'under-five deaths ',
 'Polio',
 'Total expenditure',
 'Diphtheria ',
 ' HIV/AIDS',
 'GDP',
 'Population',
 ' thinness  1-19 years',
 ' thinness 5-9 years',
 'Income composition of resources',
 'Schooling']

In [211]:
# Step 4: In ra bảng thống kê mô tả
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [212]:
# Step 5: Xóa cột Hepatitis B và Population
df.drop(['Hepatitis B', 'Population'], axis=1, inplace=True)
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,11.0,11.2,0.434,9.8

In [213]:
# Step 6: Chuyển đổi cột Status sang dạng số
df['Status'] = df['Status'].map({'Developing': 0, 'Developed': 1})
df.head(120)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,0,65.0,263.0,62,0.01,71.279624,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,17.2,17.3,0.479,10.1
1,Afghanistan,2014,0,59.9,271.0,64,0.01,73.523582,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,17.5,17.5,0.476,10.0
2,Afghanistan,2013,0,59.9,268.0,66,0.01,73.219243,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,17.7,17.7,0.470,9.9
3,Afghanistan,2012,0,59.5,272.0,69,0.01,78.184215,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,17.9,18.0,0.463,9.8
4,Afghanistan,2011,0,59.2,275.0,71,0.01,7.097109,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,Australia,2012,1,82.3,61.0,1,10.03,11714.998580,199,65.0,1,92.0,9.36,92.0,0.1,67677.634770,0.6,0.6,0.930,20.1
116,Australia,2011,1,82.0,63.0,1,10.30,10986.265270,190,64.4,1,92.0,9.20,92.0,0.1,62245.129000,0.6,0.6,0.927,19.8
117,Australia,2010,1,81.9,64.0,1,10.52,8875.786493,70,63.9,1,92.0,9.20,92.0,0.1,51874.848000,0.7,0.6,0.927,19.5
118,Australia,2009,1,81.7,66.0,1,10.62,7172.275229,104,63.4,1,92.0,9.50,92.0,0.1,42742.998980,0.7,0.6,0.925,19.1
119,Australia,2008,1,81.3,66.0,1,10.76,8547.292357,65,62.9,1,92.0,8.78,92.0,0.1,49664.685400,0.7,0.6,0.921,19.1

In [214]:
# Step 7: Đổi tên cột thinness 1-19 years thành thinness 10-19 years
df.rename(columns={' thinness  1-19 years': 'thinness 10-19 years'}, inplace=True)
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,thinness 10-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,0,65.0,263.0,62,0.01,71.279624,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,17.2,17.3,0.479,10.1
1,Afghanistan,2014,0,59.9,271.0,64,0.01,73.523582,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,17.5,17.5,0.476,10.0
2,Afghanistan,2013,0,59.9,268.0,66,0.01,73.219243,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,17.7,17.7,0.470,9.9
3,Afghanistan,2012,0,59.5,272.0,69,0.01,78.184215,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,17.9,18.0,0.463,9.8
4,Afghanistan,2011,0,59.2,275.0,71,0.01,7.097109,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,0,44.3,723.0,27,4.36,0.000000,31,27.1,42,67.0,7.13,65.0,33.6,454.366654,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,0,44.5,715.0,26,4.06,0.000000,998,26.7,41,7.0,6.52,68.0,36.7,453.351155,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,0,44.8,73.0,25,4.43,0.000000,304,26.3,40,73.0,6.53,71.0,39.8,57.348340,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,0,45.3,686.0,25,1.72,0.000000,529,25.9,39,76.0,6.16,75.0,42.1,548.587312,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,0,46.0,665.0,24,1.68,0.000000,1483,25.5,39,78.0,7.10,78.0,43.5,547.358878,11.0,11.2,0.434,9.8

In [215]:
# Step 8: Lấy tất cả các cột ngoại trừ Life Expectancy, chuyển sang mảng NumPy
x = df.drop('Life expectancy ', axis=1).values
x

array([['Afghanistan', 2015, 0, ..., 17.3, 0.479, 10.1],
       ['Afghanistan', 2014, 0, ..., 17.5, 0.476, 10.0],
       ['Afghanistan', 2013, 0, ..., 17.7, 0.47, 9.9],
       ...,
       ['Zimbabwe', 2002, 0, ..., 1.3, 0.427, 10.0],
       ['Zimbabwe', 2001, 0, ..., 1.7, 0.427, 9.8],
       ['Zimbabwe', 2000, 0, ..., 11.2, 0.434, 9.8]], dtype=object)

In [216]:
# Step 9: Lấy cột Life Expectancy, chuyển sang mảng NumPy
y = df['Life expectancy '].values
y

array([65. , 59.9, 59.9, ..., 44.8, 45.3, 46. ])

In [217]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"D:\HK252\DeepLearning\howlongwelive.csv")
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

## Handling missing data

### np.nan

In [218]:
print("Type of np.nan: ", type(np.nan))
print("Np nan - 1:     ", np.nan - 1) #any operation with nan is nan

Type of np.nan:  <class 'float'>
Np nan - 1:      nan

In [219]:
vals2 = np.array([1, np.nan, 3, 4])
print("Sum:    ", vals2.sum())
print("Nansum: ", np.nansum(vals2))
print("Nanmin: ", np.nanmin(vals2))
print("Nanmax: ", np.nanmax(vals2))

Sum:     nan
Nansum:  8.0
Nanmin:  1.0
Nanmax:  4.0

### Create a pd series with np.nan and None

In [220]:
dfs = pd.Series([1, None, np.nan])
print("Pandas automatically convert None to nans")
print(dfs)

Pandas automatically convert None to nans
0    1.0
1    NaN
2    NaN
dtype: float64

In [221]:
dfs = pd.Series(["Hello", None, np.nan])
print("Pandas do not, since String is object")
print(dfs)

Pandas do not, since String is object
0    Hello
1     None
2      NaN
dtype: object

In [222]:
dfs = pd.Series([True, None, np.nan])
print("Pandas do not, cast Boolean to object")
print(dfs)

Pandas do not, cast Boolean to object
0    True
1    None
2     NaN
dtype: object

### isnull()

In [223]:
#isnull() - check any missing values
dfs = pd.Series([1, np.nan, "hello", None])
print("Is null: ", dfs.isnull())

Is null:  0    False
1     True
2    False
3     True
dtype: bool

### not null

In [224]:
print("==Only data not null==")
print(dfs[dfs.notnull()])

==Only data not null==
0        1
2    hello
dtype: object

### dropna()

In [225]:
print("==Drop all na==")
print(dfs.dropna())  #this is not in place!
print(dfs)  #this will bring back the old copy

==Drop all na==
0        1
2    hello
dtype: object
0        1
1      NaN
2    hello
3     None
dtype: object

In [226]:
#drop columns with na, use axis = 1
df = pd.DataFrame([[1, np.nan, 2],
                  [2, 3, 5],
                  [np.nan, 4, np.nan],
                  [4, np.nan, np.nan]])

print(df.dropna(axis=1))  #default is axis = 0

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [227]:
#drop columns, if all values is nan
df[3] = np.nan  #create new column
print(df.dropna(axis=1, how="all"))

     0    1    2
0  1.0  NaN  2.0
1  2.0  3.0  5.0
2  NaN  4.0  NaN
3  4.0  NaN  NaN

### fillna()

In [228]:
# most of the time, if you have missing values, it is advised
# to drop them.  This is against many opinions.  
# However, the case is that:
# When you replace missing value with mean, you lower the variance
# When you replace with median, you also lower the variance
# when you replace with some value, you introduce noise
# but first, let's see how to replace value

print("==Fill na with 0==")
print(df.fillna(0))  #not in place, reminders!

print("==Fill all na with mean==")
print(df.fillna(df.mean()))

print("replace df.mean() for col 1 with in place")
df[1].fillna(df[1].mean(), inplace=True)  #this is in place!
print(df)

print("==Interpolate==")
print(df.interpolate(method='values'))

==Fill na with 0==
     0    1    2    3
0  1.0  0.0  2.0  0.0
1  2.0  3.0  5.0  0.0
2  0.0  4.0  0.0  0.0
3  4.0  0.0  0.0  0.0
==Fill all na with mean==
          0    1    2   3
0  1.000000  3.5  2.0 NaN
1  2.000000  3.0  5.0 NaN
2  2.333333  4.0  3.5 NaN
3  4.000000  3.5  3.5 NaN
replace df.mean() for col 1 with in place
     0    1    2   3
0  1.0  3.5  2.0 NaN
1  2.0  3.0  5.0 NaN
2  NaN  4.0  NaN NaN
3  4.0  3.5  NaN NaN
==Interpolate==
     0    1    2   3
0  1.0  3.5  2.0 NaN
1  2.0  3.0  5.0 NaN
2  3.0  4.0  5.0 NaN
3  4.0  3.5  5.0 NaN

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21252\3126589117.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[1].fillna(df[1].mean(), inplace=True)  #this is in place!

### Dataframe concatenation

In [229]:
data_numpy    = np.random.rand(3, 2)  #shape 3, 2
index         = ['Bangkok', 'Chiangmai', 'Samut Prakan']
columns       = ['Population', 'Area']
pd_from_numpy = pd.DataFrame(data_numpy, index=index, columns=columns)
print("==First dataframe==")
print(pd_from_numpy)

data_numpy2    = np.random.rand(4, 3)
index2         = ['Bangkok', 'Chiangmai', 'Samut Prakan', 'Pathum Thani']
columns2       = ['HDI', 'Temperature', 'GDP']
pd_from_numpy2 = pd.DataFrame(data_numpy2, index=index2, columns=columns2)
print("==Second dataframe==")
print(pd_from_numpy2)

# do you see something weird, the index is duplicated!
# this is because pandas preserve indices!
# however, the columns are not duplicated...as you can see
print("==Normal concat along axis 1==")
print(pd.concat([pd_from_numpy, pd_from_numpy2], axis=1)) # default join='outer' # in this case it means Full outer join

==First dataframe==
              Population      Area
Bangkok         0.615274  0.570624
Chiangmai       0.291624  0.785738
Samut Prakan    0.727484  0.173872
==Second dataframe==
                   HDI  Temperature       GDP
Bangkok       0.490070     0.941474  0.777048
Chiangmai     0.561902     0.110274  0.882361
Samut Prakan  0.670981     0.051877  0.398262
Pathum Thani  0.426750     0.961298  0.325174
==Normal concat along axis 1==
              Population      Area       HDI  Temperature       GDP
Bangkok         0.615274  0.570624  0.490070     0.941474  0.777048
Chiangmai       0.291624  0.785738  0.561902     0.110274  0.882361
Samut Prakan    0.727484  0.173872  0.670981     0.051877  0.398262
Pathum Thani         NaN       NaN  0.426750     0.961298  0.325174

### Join inner

In [230]:
print("==Concat with join inner==")
print(pd.concat([pd_from_numpy, pd_from_numpy2], axis=1, join='inner'))

==Concat with join inner==
              Population      Area       HDI  Temperature       GDP
Bangkok         0.615274  0.570624  0.490070     0.941474  0.777048
Chiangmai       0.291624  0.785738  0.561902     0.110274  0.882361
Samut Prakan    0.727484  0.173872  0.670981     0.051877  0.398262

## Merging Datasets with ID

In [231]:
left = pd.DataFrame({'ID': ['001', '002', '003', '005'],
                      'DS': ['B', 'B', 'B', 'C+'],
                      'SAD': ['A', 'B', 'C+', 'F']})
left

    ID  DS SAD
0  001   B   A
1  002   B   B
2  003   B  C+
3  005  C+   F

In [232]:
right = pd.DataFrame({'ID': ['001', '002', '003', '004'],
                      'HCI': ['B+', 'A', 'A', 'B+'],
                      'SDQI': ['A', 'A', 'B+', 'B']})
right

    ID HCI SDQI
0  001  B+    A
1  002   A    A
2  003   A   B+
3  004  B+    B

In [233]:
#seems like 004 is gone!  Very similar to inner join
result = pd.merge(left, right, on='ID')  #default is how=inner
result

    ID DS SAD HCI SDQI
0  001  B   A  B+    A
1  002  B   B   A    A
2  003  B  C+   A   B+

In [234]:
#specify how=outer
result = pd.merge(left, right, on='ID', how="outer")  #default is how=inner
result

    ID   DS  SAD  HCI SDQI
0  001    B    A   B+    A
1  002    B    B    A    A
2  003    B   C+    A   B+
3  004  NaN  NaN   B+    B
4  005   C+    F  NaN  NaN

In [235]:
#specify how=left, or right
result = pd.merge(left, right, on='ID', how="left")  #default is how=inner
result

    ID  DS SAD  HCI SDQI
0  001   B   A   B+    A
1  002   B   B    A    A
2  003   B  C+    A   B+
3  005  C+   F  NaN  NaN

## Aggregation

In [236]:
df = pd.DataFrame([('bird', 'Falconiformes', 389.0),
                    ('bird', 'Psittaciformes', 24.0),
                    ('mammal', 'Carnivora', 80.2),
                    ('mammal', 'Primates', np.nan),
                    ('mammal', 'Carnivora', 58)],
                   index=['falcon', 'parrot', 'lion', 'monkey', 'leopard'],
                   columns=('class', 'order', 'max_speed'))
df

          class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [237]:
grouped = df.groupby('class')  #return a special view as DataFrameGroupByObject
grouped.sum()

                              order  max_speed
class
bird    FalconiformesPsittaciformes      413.0
mammal   CarnivoraPrimatesCarnivora      138.2

In [238]:
grouped = df.groupby('order')  #return a special view as DataFrameGroupByObject
grouped.sum()

                       class  max_speed
order
Carnivora       mammalmammal      138.2
Falconiformes           bird      389.0
Primates              mammal        0.0
Psittaciformes          bird       24.0

In [239]:
grouped = df.groupby(['class', 'order'])
grouped.sum()

                       max_speed
class  order
bird   Falconiformes       389.0
       Psittaciformes       24.0
mammal Carnivora           138.2
       Primates              0.0

In [240]:
df.groupby(['class'])['max_speed'].median()

class
bird      206.5
mammal     69.1
Name: max_speed, dtype: float64

In [241]:
# import seaborn as sns
# planets = sns.load_dataset('planets')
# print("Shape: ", planets.shape)
# print("First five rows: ")
# print(planets.head())

# print("==Built in Pandas simple aggregations==")
# print(planets.mean())
# # print(planets.median())
# # print(planets.min())
# # print(planets.max())
# # print(planets.std())
# # print(planets.var())
# # print(planets.sum())

# print("==Mean (axis=1)==")
# print(planets.mean(axis=1))

# print("==Describe==")
# print(planets.describe())

In [242]:
planets.groupby('method').sum()

NameError: name 'planets' is not defined

In [ ]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [ ]:
# The GroupBy object supports direct iteration over the groups, 
# returning each group as a Series or DataFrame:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)

In [ ]:
planets.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

GroupBy objects have aggregate(), filter(), transform(), and apply() methods that efficiently implement a variety of useful operations before combining the grouped data.  For the purpose of the following subsections, we'll use this DataFrame:

In [ ]:
# aggregate() can take a string, a function or a list thereof, and compute
# all aggregates at once
planets.groupby('method')['orbital_period'].aggregate(
    ['min', np.median, max, np.mean, np.std, 'count'])

,min,median,max,mean,std,count
method,,,,,,
Astrometry,246.360000,631.180000,1016.000000,631.180000,544.217663,2
Eclipse Timing Variations,1916.250000,4343.500000,10220.000000,4751.644444,2499.130945,9
Imaging,4639.150000,27500.000000,730000.000000,118247.737500,213978.177277,12
Microlensing,1825.000000,3300.000000,5100.000000,3153.571429,1113.166333,7
Orbital Brightness Modulation,0.240104,0.342887,1.544929,0.709307,0.725493,3
Pulsar Timing,0.090706,66.541900,36525.000000,7343.021201,16313.265573,5
Pulsation Timing Variations,1170.000000,1170.000000,1170.000000,1170.000000,NaN,1
Radial Velocity,0.736540,360.200000,17337.500000,823.354680,1454.926210,553
Transit,0.355000,5.714932,331.600590,21.102073,46.185893,397
Transit Timing Variations,22.339500,57.011000,160.000000,79.783500,71.599884,3

In [ ]:
# take only elements that belong to group with x orbital period of std less than 3
new_planets = planets.groupby('method').filter(lambda x: x['orbital_period'].std() < 3)
new_planets.head()

,method,number,orbital_period,mass,distance,year
787,Orbital Brightness Modulation,2,0.240104,NaN,1180.0,2011
788,Orbital Brightness Modulation,2,0.342887,NaN,1180.0,2011
792,Orbital Brightness Modulation,1,1.544929,NaN,NaN,2013

In [ ]:
# look at each record
new_planets.loc[787]

method            Orbital Brightness Modulation
number                                        2
orbital_period                         0.240104
mass                                        NaN
distance                                 1180.0
year                                       2011
Name: 787, dtype: object

In [ ]:
# perform apply for each group
planets.groupby('method').apply(lambda x: x.describe())

                                 number  orbital_period  mass     distance  \
method
Astrometry                count    2.00        2.000000   0.0     2.000000
                          mean     1.00      631.180000   NaN    17.875000
                          std      0.00      544.217663   NaN     4.094148
                          min      1.00      246.360000   NaN    14.980000
                          25%      1.00      438.770000   NaN    16.427500
...                                 ...             ...   ...          ...
Transit Timing Variations min      2.00       22.339500   NaN   339.000000
                          25%      2.00       39.675250   NaN   597.000000
                          50%      2.00       57.011000   NaN   855.000000
                          75%      2.25      108.505500   NaN  1487.000000
                          max      3.00      160.000000   NaN  2119.000000

                                       year
method
Astrometry                count     2.00000
                          mean   2011.50000
                          std       2.12132
                          min    2010.00000
                          25%    2010.75000
...                                     ...
Transit Timing Variations min    2011.00000
                          25%    2011.75000
                          50%    2012.50000
                          75%    2013.25000
                          max    2014.00000

[80 rows x 5 columns]

In [ ]:
# we can also do something fancy like this
grouped = planets.groupby('method')['orbital_period']

def some_func(group):
    return pd.DataFrame({'original': group,
                        'demeaned': group - group.mean()})

grouped.apply(some_func)

C:\Users\anhng\AppData\Local\Temp\ipykernel_23392\1369668585.py:8: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  grouped.apply(some_func)

        original    demeaned
0     269.300000 -554.054680
1     874.774000   51.419320
2     763.000000  -60.354680
3     326.030000 -497.324680
4     516.220000 -307.134680
...          ...         ...
1030    3.941507  -17.160566
1031    2.615864  -18.486209
1032    3.191524  -17.910549
1033    4.125083  -16.976990
1034    4.187757  -16.914316

[1035 rows x 2 columns]

## Bài Tập 2

1. Kiểm tra xem mỗi cột có bao nhiêu giá trị bị thiếu (missing data / NaN).

2. Xử lý tất cả dữ liệu bị thiếu bằng cách thay thế bằng giá trị trung bình (mean) của từng cột tương ứng.

3. Thực hiện groupby theo quốc gia (Country).

    - Quốc gia nào có tuổi thọ trung bình thấp nhất?

    - Quốc gia nào có tuổi thọ trung bình cao nhất?

4. Thực hiện groupby theo Status (Developed / Developing).

    - Có sự khác biệt rõ rệt nào về tuổi thọ trung bình giữa các quốc gia phát triển và đang phát triển hay không?

5. Tạo một DataFrame mới bằng tay gồm 2 cột:

    - Cột thứ nhất là ID, có giá trị giống với cột Country

    - Cột thứ hai là Noise_level, điền giá trị ngẫu nhiên (tùy ý)

6. Gộp (merge) hai DataFrame lại với nhau dựa trên cột ID.

In [262]:
import pandas as pd
import numpy as np 
df = pd.read_csv("D:\HK252\DeepLearning\howlongwelive.csv")

In [261]:
#1. Kiểm tra xem mỗi cột có bao nhiêu giá trị bị thiếu (missing data / NaN).
df.isnull().sum()

Country                            0
Year                               0
Status                             0
Life expectancy                    0
Adult Mortality                    0
infant deaths                      0
Alcohol                            0
percentage expenditure             0
Hepatitis B                        0
Measles                            0
 BMI                               0
under-five deaths                  0
Polio                              0
Total expenditure                  0
Diphtheria                         0
 HIV/AIDS                          0
GDP                                0
Population                         0
 thinness  1-19 years              0
 thinness 5-9 years                0
Income composition of resources    0
Schooling                          0
ID                                 0
Noise_level                        0
dtype: int64

In [250]:
#2. Xử lý tất cả dữ liệu bị thiếu bằng cách thay thế bằng giá trị trung bình (mean) của từng cột tương ứng.
df = df.fillna(df.mean(numeric_only=True))
df

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [251]:
#3. Thực hiện groupby theo quốc gia (Country).
    #- Quốc gia nào có tuổi thọ trung bình thấp nhất?
    #- Quốc gia nào có tuổi thọ trung bình cao nhất?

country = df.groupby('Country')['Life expectancy '].mean()
print(country.idxmin())
print(country.idxmax())

Sierra Leone
Japan

In [252]:
#4. Thực hiện groupby theo Status (Developed / Developing).
    #- Có sự khác biệt rõ rệt nào về tuổi thọ trung bình giữa các quốc gia phát triển và đang phát triển hay không?
status = df.groupby('Status')['Life expectancy '].mean()
status

Status
Developed     79.197852
Developing    67.120177
Name: Life expectancy , dtype: float64

In [258]:
#5. Tạo một DataFrame mới bằng tay gồm 2 cột:

    #- Cột thứ nhất là ID, có giá trị giống với cột Country

    #- Cột thứ hai là Noise_level, điền giá trị ngẫu nhiên (tùy ý)
      
unique_countries = df['Country'].unique()
noise_df = pd.DataFrame({'ID': unique_countries,'Noise_level': np.random.rand(len(unique_countries))})
noise_df

                                     ID  Noise_level
0                           Afghanistan     0.728124
1                               Albania     0.804306
2                               Algeria     0.630284
3                                Angola     0.272361
4                   Antigua and Barbuda     0.003143
..                                  ...          ...
188  Venezuela (Bolivarian Republic of)     0.469528
189                            Viet Nam     0.480332
190                               Yemen     0.483070
191                              Zambia     0.441251
192                            Zimbabwe     0.377564

[193 rows x 2 columns]

In [259]:
#6. Gộp (merge) hai DataFrame lại với nhau dựa trên cột ID.
df['ID'] = df['Country']
df = pd.merge(df, noise_df, on='ID')
df[['Country', 'ID', 'Noise_level']]

          Country           ID  Noise_level
0     Afghanistan  Afghanistan     0.728124
1     Afghanistan  Afghanistan     0.728124
2     Afghanistan  Afghanistan     0.728124
3     Afghanistan  Afghanistan     0.728124
4     Afghanistan  Afghanistan     0.728124
...           ...          ...          ...
2933     Zimbabwe     Zimbabwe     0.377564
2934     Zimbabwe     Zimbabwe     0.377564
2935     Zimbabwe     Zimbabwe     0.377564
2936     Zimbabwe     Zimbabwe     0.377564
2937     Zimbabwe     Zimbabwe     0.377564

[2938 rows x 3 columns]